export const fonts = {
  display01: {
    fontSize: '54px',
    fontWeight: '700',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  display02: {
    fontSize: '28px',
    fontWeight: '700',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  title01: {
    fontSize: '28px',
    fontWeight: '600',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  title02: {
    fontSize: '28px',
    fontWeight: '300',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  title03: {
    fontSize: '24px',
    fontWeight: '700',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  title04: {
    fontSize: '24px',
    fontWeight: '600',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  subtitle01: {
    fontSize: '20px',
    fontWeight: '700',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  subtitle02: {
    fontSize: '20px',
    fontWeight: '600',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  subtitle03: {
    fontSize: '20px',
    fontWeight: '500',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  subtitle04: {
    fontSize: '20px',
    fontWeight: '400',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  subtitle05: {
    fontSize: '18px',
    fontWeight: '700',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  subtitle06: {
    fontSize: '18px',
    fontWeight: '400',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  body01: {
    fontSize: '16px',
    fontWeight: '700',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  body02: {
    fontSize: '16px',
    fontWeight: '500',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  body03: {
    fontSize: '16px',
    fontWeight: '400',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  body04: {
    fontSize: '14px',
    fontWeight: '700',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  body05: {
    fontSize: '14px',
    fontWeight: '400',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  caption01: {
    fontSize: '12px',
    fontWeight: '700',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
  caption02: {
    fontSize: '12px',
    fontWeight: '400',
    lineHeight: '140%',
    letterSpacing: '0%',
  },
};
